### ISSUE TITLE
Validation

### ISSUE THREAD

**Issue by vwadia** [jaekookang/p2fa_py3#13]
Hello! How did you/do you validate your results? For example, for a given text file how does one know that the transcription is correct? When you were writing this did you just compare the output to other versions of the aligner? Thank you for writing this! It's so much easier to set up and use than other versions.

**Comment by jaekookang** [comment]
To know that the given transcription is correct, I think you need the human labeler's ground-truth transcription (with temporal alignment information). I didn't develop p2fa myself. It's already been developed by a group at UPENN ([link](https://web.sas.upenn.edu/phonetics-lab/)). I guess you can definitely compare the performance of different aligners with human labelers' ground-truth alignments.

**Comment by vwadia** [comment]
Understood. Thank you! I'll go ahead and close this now.
