### ISSUE TITLE
Supporting languages other than English

### ISSUE THREAD

**Issue by bing-jian** [jaekookang/p2fa_py3#4]
Hi Jaekoo,

Does this forced alignment tool support languages other than English, for example, Chinese?

Thanks,
Bing

**Comment by jaekookang** [comment]
P2FA does not support languages other than English. You may check Montreal forced aligner if you haven't (link: [https://montreal-forced-aligner.readthedocs.io/en/latest/](https://montreal-forced-aligner.readthedocs.io/en/latest/)).
