### ISSUE TITLE
Long audio suggestion

### ISSUE THREAD

**Issue by anandcu3** [jaekookang/p2fa_py3#5]
I'm trying to run the aligner on long audio files (~1 hour long) and this takes a lot of time to complete. I can see that most of the time is for HVite to complete. Are there any parameters that I can change to accelerate the process. Do you have any suggestions? Thanks!

**Comment by jaekookang** [comment]
Hi. I think you can probably split your one-hour long file into multiple small files (eg. per sentence or utterance) to speed things up and to circumvent possible errors. I don’t think there are any parameters to change to accelerate the process as far as I know. The newer version of HTK supports GPU, but I haven’t tested it myself. 

Best,
Jaekoo

**Comment by anandcu3** [comment]
Hi @jaekookang , So I analyzed the runtimes a bit and noticed that the maximum time consumed is by the Viterbi algorithm in HTK (HVite) and added a parameter `-t`. This is the excerpt from the docs. Modifying this helped me.  

`
-t f [i l] Enable beam searching such that any model whose maximum log probability token
falls more than f below the maximum for all models is deactivated. Setting f to 0.0 disables
the beam search mechanism (default value 0.0). In alignment mode two extra parameters
i and l can be specified. If the alignment fails at the initial pruning threshold f, then the
threshold will by increased by i and the alignment will be retried. This procedure is repeated
until the alignment succeeds or the threshold limit l is reached.
`

Thanks!
