### ISSUE TITLE
skipping word .... .... ...

### ISSUE THREAD

**Issue by AhmadManzoor** [jaekookang/p2fa_py3#7]
thank you @jaekookang  for sharing your work. i am trying to generate visemes . but the least i could get is generating phonemes by your repo. but it is giving me this
_SKIPPING WORD COFFEEMAKER
SKIPPING WORD HARDER”
SKIPPING WORD IRRITATION”
SKIPPING WORD CARRIE”
SKIPPING WORD “
SKIPPING WORD WHAT”
SKIPPING WORD “
SKIPPING WORD DON’T
SKIPPING WORD THERE”
SKIPPING WORD THEM”
SKIPPING WORD I’M
SKIPPING WORD SORRY”
SKIPPING WORD HARD”
SKIPPING WORD IT”
SKIPPING WORD SAID”
SKIPPING WORD I’M
SKIPPING WORD SHOULDN’T
SKIPPING WORD HELP”
SKIPPING WORD FRONT”
SKIPPING WORD OK”
SKIPPING WORD NODDED”
SKIPPING WORD YOU’LL
SKIPPING WORD IT”
SKIPPING WORD “
SKIPPING WORD DON’T
SKIPPING WORD KNOW”
SKIPPING WORD “
SKIPPING WORD DON’T
SKIPPING WORD YOU’VE
SKIPPING WORD DECIDED”
SKIPPING WORD “
SKIPPING WORD GUESS”
SKIPPING WORD DIDN’T
SKIPPING WORD I’D
SKIPPING WORD LAND”
SKIPPING WORD GOD”
SKIPPING WORD QUIETLY”
SKIPPING WORD GOD”
SKIPPING WORD EYE”
SKIPPING WORD TOMORROW”
SKIPPING WORD HEAD”
SKIPPING WORD THAT’S
SKIPPING WORD SEWING”
SKIPPING WORD COULDN’T
SKIPPING WORD COULDN’T
SKIPPING WORD JAMIE—IT
SKIPPING WORD …
SKIPPING WORD I’D
SKIPPING WORD WHATEVER—MY
SKIPPING WORD HEART—AND
SKIPPING WORD SHE’D
SKIPPING WORD THERE’D
SKIPPING WORD DIDN’T
SKIPPING WORD AND-SO
SKIPPING WORD AND-SUCH
SKIPPING WORD SHE’D
SKIPPING WORD DONE—I
SKIPPING WORD DIDN’T
SKIPPING WORD …
SKIPPING WORD SHE’D
SKIPPING WORD BEEN—AND
SKIPPING WORD THERE’D
SKIPPING WORD MOTHER—WHAT
SKIPPING WORD SAY”
SKIPPING WORD WRONG”
and this is a long list
what do you think could be the problem and how can i solve it.

### Question 2
As i am trying to generate viseme, do you think i can use this table 
![image](https://user-images.githubusercontent.com/38387323/101416926-a543b200-390c-11eb-98a4-dda50bed1b99.png)
to map phonemes to visemes.

I will really appreciate any help.

Thanks

**Comment by jaekookang** [comment]
Hi, for your first question, I think you may need to check your word list first. As you can see, those skipping words have symbols or quotation marks combined with words. These are often separated or deleted before running the forced alignment. 
For the second question, I'm not an expert on the use of visemes, but the mapping between visemes and phonemes looks reasonable to me at least.

**Comment by AhmadManzoor** [comment]
ok i will see on that. Thank you so much for your response, i really appreciate that
